CREATE TABLE Cours (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL, 
  ueId INT NOT NULL, 
  notes TEXT NULL,  
  dateDebut DATE NOT NULL, 
  dateFin DATE NOT NULL, 
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ueId) REFERENCES UEs(id) ON DELETE CASCADE 
);