CREATE TABLE Retours (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contenu TEXT NOT NULL,
  eleveId INT NOT NULL,
  coursId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (eleveId) REFERENCES Eleves(id),
  FOREIGN KEY (ueId) REFERENCES UEs(id)
);
