CREATE TABLE archive_retours (
  id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  retour_id BIGINT(20) UNSIGNED NOT NULL,
  archived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (retour_id) REFERENCES retours(id) ON DELETE CASCADE
);