CREATE TABLE ArchiveRetours (
  id INT AUTO_INCREMENT PRIMARY KEY,
  retourId INT NOT NULL,
  archivedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (retourId) REFERENCES Retours(id)
);
